### PR TITLE
Parsing and writing support for variable font tables fvar, STAT and avar

### LINKED ISSUE #573: fvar table is parsed and can be generated, but is never actually written to a file
## Expected Behavior

An existing fvar table should be written to the output file

## Current Behavior

fvar is parsed, we also already have a make function for it which is even being tested, but the table is never actually written to the file.

## Possible Solution

I'm working on read/write support for other tables related to variable fonts. I'll add fvar writing while I'm at it, but I'll need to adapt it to the new platform-agnostic name table structure, as the fvar table adds entries there.

## Steps to Reproduce (for bugs)

1. Open a font that has an fvar table
2. font.download()
3. Re-open the downlaoded font
4. var table is missing

## Your Environment

* Version used: master
* Font used: Selawik-variable and Inconsolata-variable
* Browser Name and version: -
* Operating System and version (desktop or mobile): -
* Link to your project: -

### PR DESCRIPTION
**Pull request by Connum**
## Description

- [X] add missing `encode.F2DOT14`
- [X] add `encode.FLOAT` as a wrapper to `encode.FIXED` when handling actual float numbers
- [X] adapt `fvar` writing to new platform-agnostic names structure (see #542)
- [X] fix `fvar` table not being written (fix #573)
- [X] add parsing and writing support for `STAT`
- [X] add parsing and writing support for `avar`
- [X] add stub for gvar parsing and writing

## Motivation and Context

This PR lays the groundwork for variable fonts support. Actual coordinate scaling and normalization (see https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview#CSN) for rendering is not yet implemented, but several tables needed for supporting it can now be parsed and written.

I decided against also implementing `gvar`, because it introduces a set of new concepts/data types and seems to be the most complex of them. That would have bloated the PR even more.

### Further resources for future rendering implementation:
* arrowtype/blog/issues/6
* https://www.axis-praxis.org/samsa/

## How Has This Been Tested?

Loading and saving different variable fonts, added tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I did `npm run test` and all tests passed green (including code styling checks).
- [X] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the **README** accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/substitution.js [hunk 1]
```diff
@@ -15,16 +16,6 @@ function Substitution(font) {
     Layout.call(this, font, 'gsub');
 }
 
-// Check if 2 arrays of primitives are equal.
```
Comment (Connum) [inline src/substitution.js:18]: this has been moved to util.js for shared use

File: src/opentype.js [hunk 2]
```diff
@@ -18,7 +18,10 @@ import cpal from './tables/cpal';
 import colr from './tables/colr';
 import cmap from './tables/cmap';
 import cff from './tables/cff';
+import STAT from './tables/STAT';
```
Comment (yne) [inline src/opentype.js:21]: could you unify to lowercase ?

**Comment by yne** [comment]
very nice addition :+1:

File: src/opentype.js (hunk 2 above)
Comment (Connum) [reply src/opentype.js]: done!

File: src/tables/avar.js [hunk 3]
```diff
@@ -0,0 +1,90 @@
+// The `avar` table stores information on how to modify a variation along a variation axis
+// https://learn.microsoft.com/en-us/typography/opentype/spec/avar
+
+import check from '../check';
```
Comment (yne) [inline src/tables/avar.js:4]: image

`npm start` with `/docs/module.html` containing :

```html
<script type=module>import * as ot from '/src/opentype.js';</script>
```

File: src/tables/stat.js [hunk 4]
```diff
@@ -0,0 +1,249 @@
+// The `STAT` table stores information on design attributes for font-style variants
+// https://learn.microsoft.com/en-us/typography/opentype/spec/STAT
+
+import check from '../check';
```
Comment (yne) [inline src/tables/stat.js:4]: same here : `.js` is missing

File: src/types.js [hunk 5]
```diff
@@ -175,6 +178,18 @@ encode.LONG = function(v) {
...
 sizeOf.LONG = constant(4);
 
+/**
+ * Convert a 64-bit JavaScript float to a 32-bit signed fixed-point number (16.16)
+ */
+encode.FLOAT = function(v) {
+    if (v > MAX_16_16 || v < MIN_16_16) {
+        throw new Error(`Value ${v} is outside the range of representable values in 16.16 format`);
+    }
+    let fixedValue = Math.round(v * (1 << 16)) << 0; // Round to nearest multiple of 1/(1<<16)
```
Comment (yne) [inline src/types.js:188]: could be `const`

**Review by yne — APPROVED** [review]
LGTM :rocket:
don't forget to fix the `import` paths before merging :+1:

**Comment by Connum** [comment]
You'll have to approve again before I can merge.
Is there a good way to catch missing file endings in imports, without having to manually test it in browser context? Maybe a linting rule?

**Review by yne — APPROVED** [review]

**Comment by yne** [comment]
@Connum  I rebase-squashed your `connum/feature/variable-font-tables` on `upstream/master` + fixed lint + minor STAT->stat renaming

All lint+test are now passing. You can merge when you are okay

**Comment by yne** [comment]
> Is there a good way to catch missing file endings in imports

Node / Deno implicitly lookup import with `.js` suffix, browser don't, so either we

- add a `eslint-plugin-import` dependency + `"import/extensions" : ["error", { "js": "always"}]` [rule](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/extensions.md)

- run a chrome in CI that `<script type=module>import 'src/opentype.js'</script>`

**Comment by Connum** [comment]
I can't approve because I'm the PR author! @ILOVEPIE? :)

**Comment by Connum** [comment]
> * add a `eslint-plugin-import` dependency + `"import/extensions" : ["error", { "js": "always"}]` [rule](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/extensions.md)

I'm all for that!

**Comment by Connum** [comment]
I just added the plugin and configured it, but strangely while VSCode does indeed show red lines under missing file extensions for import statements, the `npm run lint` command does not. When I change `"always"` to `"never"`, it shows errors for all other import statements, however. I stumbled upon https://github.com/import-js/eslint-plugin-import/issues/2319 which brought me to https://github.com/satazor/eslint-plugin-import-esm - but it's exactly the same, with VS Code doing what it's supposed to do, but the lint command failing. I have no clue what's happening here!

**Comment by yne** [comment]
maybe the best testing would be to have in CI a chrome-headless test that import the /src/opentype.js :)

**Comment by Connum** [comment]
I just added #584 with a custom eslint rule for enforcing file extensions in import paths.
